### ISSUE TITLE
[Bug] unable to install docker on raspberry pi

### ISSUE THREAD

**Issue by giant2179** [aymene69/stremio-jackett#100]
**Describe the bug**
The script is failing to install docker and gives an error that the repository does not have a release file. From reading the errors, it appears the script is looking for an Ubuntu version of docker to install, not a Debian version. I installed docker with these instructions (https://linuxiac.com/how-to-install-docker-on-debian-12-bookworm/) and then was able to run the rest of the self host script

**To Reproduce**
Steps to reproduce the behavior: install script on Debian based Linux

**Expected behavior**
For the script to install docker

**Screenshots**

**Your system info (please complete the following information):**
 - OS: [e.g. Ubuntu] Debian bookworm 64bit on raspberry pi 3b
 - Browser [e.g. chrome, safari] na
 - Version [e.g. 22] na
 - Docker or Node ? Docker
 - Realdebrid? Torrent?

**Additional context**

**Comment by aymene69** [comment]
This is not docker support.

**Comment by giant2179** [comment]
Hey, I was reporting it because it was the result of running your script to
install docker. I thought there might be something missing that is included
in the link I used that would help.
