### ISSUE TITLE
[Bug] There is no just "torrent/magnet" option?

### ISSUE THREAD

**Issue by 9acca9** [aymene69/stremio-jackett#104]
HI.
Until 2.1.6 version there was the option to use just torrent... now it seems that you need RD or AD... and i dont have that. Im from Latinamerica and for us there is no need to use RD or AD.
So, it is possible to add that option again? 
Thanks!

p.s. without that....... of course, i cant use it.

**Comment by aymene69** [comment]
It's being rewrited

**Comment by bertin0** [comment]
> It's being rewrited

could you update the readme to reflect this in the meantime please? would've been nice to know before setting up haha

**Comment by 9acca9** [comment]
Hi. This option is working again in 4.0?
i just try to see, but when click over install i get a response like "please fill all the fields" because i dont have a RD/etc API Key. If i just put some random thing i cant install but the addon give erros when searching (probably because still is not working)
Just asking.
Thanks!

**Comment by davidemarcoli** [comment]
Hi @9acca9 
At the moment it only works with a debrid API key and just displays additional results. But I agree that that doesn't really make sense and you should be able to only use torrenting without a paid debrid service. I'm gonna work on it when I have time

**Comment by aymene69** [comment]
Added
