### ISSUE TITLE
Offcloud.com api integration

### ISSUE THREAD

**Issue by bijfy** [aymene69/stremio-jackett#13]
Any way it's possible to add offcloud.com debrid service it's something like realdrid

https://github.com/Offcloud/offcloud-api

https://offcloud.com

**Comment by ragmehos** [comment]
Yes please for offcloud

**Comment by aymene69** [comment]
This service seems to be under-used by the community. I do not plan on making it available for the moment, if not anytime soon. Thanks.

**Comment by bijfy** [comment]
@aymene69 or please atleast guide us  , how to add if we fork your repo ?? Please please please

**Comment by aymene69** [comment]
> @aymene69 Can one of us add it and send a pull request for review? Is that ok? 

You can PR if you want

**Comment by Blockr22** [comment]
would luv offcloud support aswell. thnx
