### ISSUE TITLE
[Bug] There is no requeriment.txt file to install

### ISSUE THREAD

**Issue by 9acca9** [aymene69/stremio-jackett#154]
So, of course the first question about the new version it is me (lol, sorry)
Well, im following the instruction to install, but i see there is no requeriment.txt, then when i make:

`pip install -r requirements.txt`
of course, i get an error.

if you can help me? 
Thanks!
And of course, like always, thanks for your work!

**Comment by MrEdinLaw** [comment]
U gotta go in the 'source' directory

**Comment by 9acca9** [comment]
lol. Thanks!

**Comment by CandyManKillerZ** [comment]
> U gotta go in the 'source' directory

Can you please explain.
