### ISSUE TITLE
[Feature request] Better anime/series search

### ISSUE THREAD

**Issue by hyoretsu** [aymene69/stremio-jackett#16]
Things to note:

- [ ] Don't use category 5070 - almost nobody seems to use it and it gives few results

Torrentio seems to do some heavy treating for anime (could also be done for series) in such a way that it seems to search for episode alone when it's the first (and only) season, resulting in far better results. For comparison, the current results' max trackers is 181.
![image](https://github.com/aymene69/stremio-jackett/assets/20804322/48823caf-1036-483f-b2e6-86820c29c855)

Another improvement is searching for the japanese (original) name, either alongside the english one or instead of it, which also tends to result in better seeders numbers.
![image](https://github.com/aymene69/stremio-jackett/assets/20804322/2c41894e-4f14-46da-a28e-2e413f5911d7)

**Comment by aymene69** [comment]
Can I get your discord @ ?

**Comment by hyoretsu** [comment]
Sure, it's also @hyoretsu.
