### ISSUE TITLE
[Feature] Allow two Debrid accounts at once

### ISSUE THREAD

**Issue by thomasmormay** [aymene69/stremio-jackett#160]
Please allow us to use 2 debrid services at once and let us know which one each link is using.
I do this with Torrentio for example because sometimes one goes down and also sometimes you can find certain shows on one and not the other.

Bonus points if you can individually set "Results Per Quality" - for example showing 1 result per quality of Real Debrid & 1 All Debrid. (or whatever 2 debrid services you choose)

**Comment by davidemarcoli** [comment]
You should be able to just install the add-on 2 times. In Torrentio you also can't select multiple debrid services on the config page, right?

**Comment by thomasmormay** [comment]
> You should be able to just install the add-on 2 times. In Torrentio you also can't select multiple debrid services on the config page, right?

This is what I'm currently doing (installing 2 versions of stremio-jackett).
It works ok but it would be much better if I could do it on 1 install.

Torrentio does in fact allow you to select/use multiple Debrid services on one install.
It also tells you which links are which Debrid service which is nice.
