### ISSUE TITLE
[Bug] Real-Debrid API instantAvaibility deactivated.

### ISSUE THREAD

**Issue by Ogekuri** [aymene69/stremio-jackett#171]
The API on https://api.real-debrid.com/rest/1.0/torrents/instantAvailability is deactivated since 21/11/2024.
 (official communication: https://x.com/RealDebrid/status/1859673163681960169)

The "result = debrid_service.get_availability_bulk(hashes, ip)" fail returning None.

**Comment by aymene69** [comment]
Work around merged
