### ISSUE TITLE
Add-on assumes https?

### ISSUE THREAD

**Issue by brianamit2017** [aymene69/stremio-jackett#18]
Hi, thank you for this great add-on.
I tried installing the latest docker image of the add-on on my server. When I try to install it to Stremio (clicking install on the configure page) I get the error "ERR_OPENING_MEDIA". After some debugging I realised Stremio is trying to access the add-on on https://192... While the add-on in http. How can I make Stremio realise it's http? Thank you

**Comment by hyoretsu** [comment]
Can you provide more details? At that part the addon doesn't actually use HTTP/HTTPS. It uses a stremio-specific slug in the form of `stremio://localhost:3000/FORM_DATA/manifest.json`
![image](https://github.com/aymene69/stremio-jackett/assets/20804322/16ddcc31-9495-4adc-b8a8-0dabee8eb7d2)
When I encountered that error though it usually had something to do with my server. (if I run it on WSL I can't access it on Windows. If I run it on WSL with Docker, I can for some reason)

**Comment by mckenna654** [comment]
![image](https://github.com/aymene69/stremio-jackett/assets/10954027/5b9338e8-b943-414d-8f4b-b308265e26d4)

I'm also getting this. I have Jackett installed and open publicy (through reverse proxy) and stremio jackett running on Unraid.
I'm trying to add it from the same LAN as the server.

**Comment by aymene69** [comment]
Hi. If locally, the addon doesnt' need https. If remotely, then yes, you'll need to reverse proxy it lie you discovered. And then, jackett needs to be served on https as well. It is a restriction made by Stremio and not us

**Comment by mckenna654** [comment]
I got it working by setting up reverse proxy however the addon DOES need https if it is running on any IP that isn't 127.0.0.1 and localhost. It is a stremio isuse.

Yes you can load it via http but you cannot add it to stremio.
