### ISSUE TITLE
Cannot GET /<redacted>/all/2000/5000/undefined/CAMHD/manifest.json

### ISSUE THREAD

**Issue by purple-emily** [aymene69/stremio-jackett#21]
Cannot GET /<redacted>/https://<redacted>/<redacted>/all/2000/5000/undefined/CAMHD,BDRIP/manifest.json

Using Caddy as a reverse proxy:

	@stremio-jacket-addon host <redacted>
	handle @stremio-jacket-addon {
		reverse_proxy stremio-jacket-addon:3000
	}

I can access the configure page but the manifest.json won't work.

I'm using Docker on a totally fresh installation.

Jackett is on the same host behind Caddy. Accessing both through a Cloudflare tunnel

**Comment by aymene69** [comment]
You are using an outdated version of the addon

**Comment by purple-emily** [comment]
@aymene69 I swear I pulled it before it went live but clearly not. Great, I just deleted it and pulled and it's newer, as you said. Thanks for your help and the addon 👍🏻

**Comment by aymene69** [comment]
No problem and thank you for using itç

**Comment by purple-emily** [comment]
I see how you figured it out, very clever! The makeup of the URL has changed! Everything works great!! Thanks for the new release

**Comment by aymene69** [comment]
Yup exactly! I changed it to a b64 one parameter to avoid the issue you just had,

You're welcome!
