### ISSUE TITLE
Feature request: sort by language

### ISSUE THREAD

**Issue by andronedev** [aymene69/stremio-jackett#23]
I'd like to be able to use it in a specific language

A bit like torrentio does

**Comment by aymene69** [comment]
What do you mean by specific language?

**Comment by hyoretsu** [comment]
I think he's talking about the "Priority foreign language" option of Torrentio. Not entirely sure what that actually does though.

**Comment by andronedev** [comment]
> I think he's talking about the "Priority foreign language" option of Torrentio. Not entirely sure what that actually does though.

Yes, with two features: 

- language flag on source title 
- possibility of sorting by language (one language has priority and others can be authorized or not)

**Comment by hyoretsu** [comment]
The first one's entirely on the Jackett server though, this extension has no control over its indexers

**Comment by aymene69** [comment]
Added
