### ISSUE TITLE
Both Node method and docker medthod stuck at 1.0.0 not the lastest ver

### ISSUE THREAD

**Issue by olivergiangvu** [aymene69/stremio-jackett#24]
Hi 
I try to install in my linux Ubuntu ssh server but somehow it stuck with the  1.0.0 ver 

![CleanShot 2024-01-25 at 12 49 32](https://github.com/aymene69/stremio-jackett/assets/106240777/074583cb-419a-48e9-a459-7b558f6e6c82)

Then it always have this err when I try to intsall add on to Stremio 
![CleanShot 2024-01-25 at 12 50 11](https://github.com/aymene69/stremio-jackett/assets/106240777/2b395060-54ef-48e1-bcf9-478f925e44c2)
I follow the instruction on the readme. Thanks!

**Comment by aymene69** [comment]
You have the latest version. The 1.0.0 is a mistake, I forgot to change it.

You can't load the link remotely if it isn't HTTPS. Please, reverse proxy it

**Comment by olivergiangvu** [comment]
yes I have all info. 2 api key and the link to Jackettt as http://192.168.50.153:9117 ( my ssh LAN IP)

**Comment by olivergiangvu** [comment]
> You entered all the details ? left no inputs blank?

Yes have all feilds filled
- AD API
- Jackett url as http://192.168.50.153:9117 - my ssh LAN IP
- Jackett API

**Comment by aymene69** [comment]
show addon logs

**Comment by olivergiangvu** [comment]
> Owner


> stremio-addon-jackett@1.0.0 start
> node src/index.js

Server is running at http://localhost:3000

> stremio-addon-jackett@1.0.0 start
> node src/index.js

Server is running at http://localhost:3000
Series request. ID: tt7678620 Name: "Bluey" Season: 01 Episode: 07
Searching on Jackett...
Will return Debrid link.
No results found.
Movie request. ID: tt11762114 Name: Mean Girls
Searching on Jackett...
Will return Debrid link.
No results found.
Movie request. ID: tt17351924 Name: Saltburn
Searching on Jackett...
Will return Debrid link.
No results found.

> stremio-addon-jackett@1.0.0 start
> node src/index.js

Server is running at http://localhost:3000

> stremio-addon-jackett@1.0.0 start
> node src/index.js

Server is running at http://localhost:3000
Movie request. ID: tt17351924 Name: Saltburn
Searching on Jackett...
Will return Debrid link.
No results found.
Movie request. ID: tt17351924 Name: Saltburn
Searching on Jackett...
Will return Debrid link.
No results found.
Series request. ID: tt12324366 Name: "Percy Jackson and the Olympians" Season: 01 Episode: 07
Searching on Jackett...
Will return Debrid link.
No results found.
Movie request. ID: tt11762114 Name: Mean Girls
Searching on Jackett...
Will return Debrid link.
No results found.
Series request. ID: tt5611024 Name: "Fool Me Once" Season: 01 Episode: 02
Searching on Jackett...
Will return Debrid link.
No results found.
Series request. ID: tt12324366 Name: "Percy Jackson and the Olympians" Season: 01 Episode: 07
Searching on Jackett...
Will return Debrid link.
No results found.
Series request. ID: tt11640018 Name: "La Brea" Season: 02 Episode: 10
Searching on Jackett...
Will return Debrid link.
No results found.
Series request. ID: tt12324366 Name: "Percy Jackson and the Olympians" Season: 01 Episode: 07
Searching on Jackett...
Will return Debrid link.
No results found.
Series request. ID: tt14203572 Name: "Monsieur Spade" Season: 01 Episode: 01
Searching on Jackett...
Will return Debrid link.
No results found.
Movie request. ID: tt16277242 Name: Society of the Snow
Searching on Jackett...
Will return Debrid link.
No results found.
Series request. ID: tt9288030 Name: "Reacher" Season: 02 Episode: 08
Searching on Jackett...
Will return Debrid link.
No results found.
Series request. ID: tt9288030 Name: "Reacher" Season: 02 Episode: 08
Searching on Jackett...
Will return Debrid link.
No results found.

**Comment by aymene69** [comment]
You have indexers in jackett ?

**Comment by olivergiangvu** [comment]
> You have indexers in jackett ?

Just add index
![CleanShot 2024-01-26 at 00 34 19](https://github.com/aymene69/stremio-jackett/assets/106240777/1a5c8a4c-4b7f-4a10-b6c1-e7a1d7cd5348)
But still no link shoe in stremio

**Comment by olivergiangvu** [comment]
Torrent info: The Walking Dead S11E03 1080p WEB H264-GGEZ
Getting AD link...
{ status: 'success', data: { magnets: [ [Object] ] } }
Magnet added to AD. ID: 220009315
Getting torrent info...
Torrent info: The Walking Dead S11E03 1080p WEB H264-GGEZ
Getting AD link...
{ status: 'success', data: { magnets: [ [Object] ] } }
Magnet added to AD. ID: 220009315
SyntaxError: Unexpected token '<', "<html>
<he"... is not valid JSON
    at JSON.parse (<anonymous>)
    at parseJSONFromBytes (node:internal/deps/undici/undici:5419:19)
    at successSteps (node:internal/deps/undici/undici:5390:27)
    at fullyReadBody (node:internal/deps/undici/undici:1501:9)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async specConsumeBody (node:internal/deps/undici/undici:5399:7)
    at async getMovieADLink (file:///app/src/helpers/getMovieADLink.js:29:18)
    at async jackettSearch (file:///app/src/jackett/index.js:56:27)
    at async file:///app/src/routes.js:67:24
SyntaxError: Unexpected token '<', "<html>
<he"... is not valid JSON
    at JSON.parse (<anonymous>)
    at parseJSONFromBytes (node:internal/deps/undici/undici:5419:19)
    at successSteps (node:internal/deps/undici/undici:5390:27)
    at fullyReadBody (node:internal/deps/undici/undici:1501:9)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async specConsumeBody (node:internal/deps/undici/undici:5399:7)
    at async getMovieADLink (file:///app/src/helpers/getMovieADLink.js:29:18)
    at async jackettSearch (file:///app/src/jackett/index.js:56:27)
    at async file:///app/src/routes.js:67:24
Selecting biggest file...
Series request. ID: tt14203572 Name: "Monsieur Spade" Season: 01 Episode: 01
Searching on Jackett...
Will return Debrid link.

**Comment by aymene69** [comment]
For Debrid, you only have one result. It will be increased in the next release, you can see it in #22

**Comment by olivergiangvu** [comment]
Thank so much for your assistance!
