### ISSUE TITLE
[Bug] Fail to Fetch error ERR_OPENING_MEDIA when trying to install

### ISSUE THREAD

**Issue by IskrenTs** [aymene69/stremio-jackett#32]
**Describe the bug**
after entering all info in the addon page and press install it opens stremio and this error appears

Fail to Fetch error ERR_OPENING_MEDIA when trying to install

Used the method from the guide

**Comment by BarristQL** [comment]
Same.. tried on Windows 

Copying the install URL to the web version of stremio allowed me to install it but the addon seemed to not work at all. And clicking configure doesn’t work.

**Comment by 9acca9** [comment]
the same for me with this setup.
I already have a server running for stuff so...... i install there JACKETT.

The stremio-jackett addon i install on my notebook with stremio app (i dont use this notebook to see movies). And proceed to install the addon, just to see how works. That works perfect! but....... i dont want to have the stremio-jackett running in my notebook so i installed in my all in hand server. And proceed to install again but this time from that server. And there i have the same error that all you.

**Comment by luigi370** [comment]
Same here, i tried from a mac and from FireTv. no success.

**Comment by aymene69** [comment]
Please can you guys show logs ? 

You have to go back to your server, type: "sudo docker ps"

Copy the ID of the container named "addon" and type "sudo docker logs ID"

Thanks a lot and sorry

**Comment by IskrenTs** [comment]
![Screenshot 2024-01-27 124436](https://github.com/aymene69/stremio-jackett/assets/106561107/5afcf335-5df6-4c5c-b743-a8497d3e3e07)
![image](https://github.com/aymene69/stremio-jackett/assets/106561107/24bd36af-d3b1-4ffe-831f-8114d7524bde)
This is the error i get in Stremio after i prss the install button
![image](https://github.com/aymene69/stremio-jackett/assets/106561107/a6b035ce-394a-48b1-a25a-55c1c09eebf1)

I dont see any log file.  IF its created somewere specifically  just tell me to get it

**Comment by Harshan-Dinuka-Gunarathne** [comment]
ubuntu@streamio-jackett:~$ sudo docker logs 1f1d03c55ac1

> stremio-addon-jackett@1.1.6 start
> node src/index.js

Server is running at http://localhost:3000/addon
Movie request. ID: tt4255304 Name: The Void
Searching on Jackett...
Will return Debrid link.
TypeError: fetch failed
    at node:internal/deps/undici/undici:12442:11
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async getItemsFromUrl (file:///app/src/jackett/utils/jackettSearch.js:11:14)
    at async jackettSearch (file:///app/src/jackett/utils/jackettSearch.js:33:15)
    at async fetchResults (file:///app/src/jackett/index.js:5:16)
    at async file:///app/src/routes.js:61:24 {
  cause: Error: self-signed certificate
      at TLSSocket.onConnectSecure (node:_tls_wrap:1674:34)
      at TLSSocket.emit (node:events:519:28)
      at TLSSocket._finishInit (node:_tls_wrap:1085:8)
      at ssl.onhandshakedone (node:_tls_wrap:871:12) {
    code: 'DEPTH_ZERO_SELF_SIGNED_CERT'
  }
}
Movie request. ID: tt4255304 Name: The Void
Searching on Jackett...
Will return Debrid link.
TypeError: fetch failed
    at node:internal/deps/undici/undici:12442:11
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async getItemsFromUrl (file:///app/src/jackett/utils/jackettSearch.js:11:14)
    at async jackettSearch (file:///app/src/jackett/utils/jackettSearch.js:33:15)
    at async fetchResults (file:///app/src/jackett/index.js:5:16)
    at async file:///app/src/routes.js:61:24 {
  cause: Error: self-signed certificate
      at TLSSocket.onConnectSecure (node:_tls_wrap:1674:34)
      at TLSSocket.emit (node:events:519:28)
      at TLSSocket._finishInit (node:_tls_wrap:1085:8)
      at ssl.onhandshakedone (node:_tls_wrap:871:12) {
    code: 'DEPTH_ZERO_SELF_SIGNED_CERT'
  }

@aymene69 hi this is the log i get

**Comment by BarristQL** [comment]
@aymene69 
Have several of these in my log. Thanks for your work!

Series request. ID: tt15557874 Name: "The Traitors" Season: 02 Episode: 01
Searching on Jackett...
Will return Debrid link.
TypeError: fetch failed
    at node:internal/deps/undici/undici:12442:11
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async getItemsFromUrl (file:///app/src/jackett/utils/jackettSearch.js:11:14)
    at async jackettSearch (file:///app/src/jackett/utils/jackettSearch.js:33:15)
    at async fetchResults (file:///app/src/jackett/index.js:5:16)
    at async file:///app/src/routes.js:77:24 {
  cause: Error: self-signed certificate
      at TLSSocket.onConnectSecure (node:_tls_wrap:1674:34)
      at TLSSocket.emit (node:events:519:28)
      at TLSSocket._finishInit (node:_tls_wrap:1085:8)
      at ssl.onhandshakedone (node:_tls_wrap:871:12) {
    code: 'DEPTH_ZERO_SELF_SIGNED_CERT'
  }
}

**Comment by BarristQL** [comment]
looks like it's ssl related, but i am not sure how to go about fixing

**Comment by aymene69** [comment]
Hi. I just pushed a fix. Can you please delete the instance you created and follow the guide once again ? It should work.

Thanks a lot and sorry!

**Comment by NunoMCP** [comment]
works like a charm, thank you for the quick fix!

**Comment by aymene69** [comment]
Super cool, enjoy ;)

**Comment by 9acca9** [comment]
Sorry, but.....is not working for me.

```
sudo docker logs c87d15c96689                                                                  

> stremio-addon-jackett@1.1.6 start
> node src/index.js

Server is running at http://localhost:3000
```

i have jackett AND the docker for stremio-jackett installed in 192.168.0.166 (my server)
I have installed the stremio app in 192.168.0.134

i can reach 192.168.0.166 from 192.168.0.134. 
If i go to  192.168.0.166:9117 i see jackett working
If i go to 192.168.0.166:3000 i see stremio-jackett working
i config there as this 
![imagen](https://github.com/aymene69/stremio-jackett/assets/25393371/6664a42f-3e07-4609-894e-26c18abc8053)
(of course that is not the API Key)

when i select "Install" i get the error "ERR_Opening_media"...

So, what can be wrong?

**Comment by aymene69** [comment]
Reverse Proxy to make it work with HTTPS

**Comment by 9acca9** [comment]
hi, thanks for the quick response.

so, it have to be HTTPS mandatory?

In the other hand. What i have to reverse proxy? jackett? stremio-jackett? both?

I already put stremio-jackett under the reverse proxy with https. And is working, i CAN INSTALL THE ADDON!!! 
But.... it dont return nothing.
I get this in the logs:
```

> stremio-addon-jackett@1.1.6 start
> node src/index.js

Server is running at http://localhost:3000
Movie request. ID: tt14253846 Name: Speak No Evil
Searching on Jackett...
Will return Torrents.
TypeError: fetch failed
    at node:internal/deps/undici/undici:12442:11
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async getItemsFromUrl (file:///app/src/jackett/utils/jackettSearch.js:11:14)
    at async jackettSearch (file:///app/src/jackett/utils/jackettSearch.js:33:15)
    at async fetchResults (file:///app/src/jackett/index.js:5:16)
    at async file:///app/src/routes.js:61:24 {
  cause: Error: connect ECONNREFUSED 192.168.0.166:9117
      at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1602:16) {
    errno: -111,
    code: 'ECONNREFUSED',
    syscall: 'connect',
    address: '192.168.0.166',
    port: 9117
  }
}
```


In the other hand (it seems i have several hands...). Just if you want to read this. In my first installation all works, that was like this:
192.168.0.166 --------- jackett server
192.168.0.134 --------- stremio-jackett and stremio app (my notebook)

i dont like that setup because of course  i want to have stremio-jackett running in the server.
BUT, in this setup all was working and i dont need reverse proxy, neither https.

Well, i write this if this help in some manner.

**Comment by 9acca9** [comment]
So, i keep trying.
Now i put all behind the reverse proxy and with https. I can reach the jackett and make a manual search.
Also can reach the stremio-jackett and install. But, still dont have any result and now i see this kind of logs, complaining also about SSL.
```
Movie request. ID: tt15398776 Name: Oppenheimer
Searching on Jackett...
Will return Torrents.
TypeError: fetch failed
    at node:internal/deps/undici/undici:12442:11
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async getItemsFromUrl (file:///app/src/jackett/utils/jackettSearch.js:11:14)
    at async jackettSearch (file:///app/src/jackett/utils/jackettSearch.js:33:15)
    at async fetchResults (file:///app/src/jackett/index.js:5:16)
    at async file:///app/src/routes.js:61:24 {
  cause: Error: unable to verify the first certificate
      at TLSSocket.onConnectSecure (node:_tls_wrap:1674:34)
      at TLSSocket.emit (node:events:519:28)
      at TLSSocket._finishInit (node:_tls_wrap:1085:8)
      at ssl.onhandshakedone (node:_tls_wrap:871:12) {
    code: 'UNABLE_TO_VERIFY_LEAF_SIGNATURE'
  }
```

But, as i say i can go to both in https.
![imagen](https://github.com/aymene69/stremio-jackett/assets/25393371/c7e75837-180a-401b-adc8-f16bb1184b66)

![imagen](https://github.com/aymene69/stremio-jackett/assets/25393371/226f0ddb-a4de-47d2-8693-7034e82bb458)

this is my jackett url now: https://www.2222222.xyz/jackett

and stremio-jackett is https://www.2222222.xyz/

Thanks!

**Comment by 9acca9** [comment]
And....... now is working!
But, i delete completely de docker and install with "git clone" / npm install / npm start

Why my config dont work with the docker and work in this manner (now i need to see how make a service from this)???? I dont know. Because as you can saw i was working with the lastest version.

Thanks again! and thanks for the beautiful colors of the background image that you use.

**Comment by luigi370** [comment]
@9acca9 I did the same installation.. both (jackets and Stremio-jackett) are working under https, however I still get the error "media not found" in Mac App. are you on windows? thanks

**Comment by tduong-cloud** [comment]
Hi,

I have installed the addon and jackett on my rpi4. Both are accessible via https.

But I can't install the addon. What information would you need to debug this ?

Many thanks for your work :).

**Comment by hyoretsu** [comment]
> Hi,
> 
> I have installed the addon and jackett on my rpi4. Both are accessible via https.
> 
> But I can't install the addon. What information would you need to debug this ?
> 
> Many thanks for your work :).

How did you set up HTTPS? Using a self-signed certificate?

**Comment by tduong-cloud** [comment]
No, I am using cosmos server, which can provide reverse proxy. it is configured with ssl certificates from Let's Encrypt and a duckdns subdomain

**Comment by 9acca9** [comment]
@luigi370 Can you share your setup? (where is installed jackett / stremio-jackett), etc.
 
> you can create a service and enable it with systemctl.

i already did, is working like a charm!
Thanks!
