### ISSUE TITLE
"RD link isn't ready. Retrying... Waiting for RD link..."

### ISSUE THREAD

**Issue by BarristQL** [aymene69/stremio-jackett#37]
**Describe the bug**
I often notice this in the docker log (i.e., hundreds of lines repeating). I'm not sure if it's causing any issues, as results do eventually show up. The search results do tend to be slower to load (~30secs) than other addons, though.

**Screenshots**
![image](https://github.com/aymene69/stremio-jackett/assets/97279898/4cdfbdaf-912f-4e80-a84e-0bcc650cfb2e)

**Your system info (please complete the following information):**
Set up using "Newbie guide"

**Comment by aymene69** [comment]
Could I get the indexer and movie/serie you were going to see ? So I can reproduce the bug. Thanks :)

**Comment by BarristQL** [comment]
Thanks! I've got a few indexers chosen, and the movie I tested it with was Barbie

**Comment by aymene69** [comment]
Can i know what indexers please ?

**Comment by BarristQL** [comment]
![image](https://github.com/aymene69/stremio-jackett/assets/97279898/0512daca-f552-4b20-b2d3-2ffd52606833)

**Comment by BarristQL** [comment]
Testing a few more times, i'm not seeing the same looping message! Could have been a temporary glitch.

 Though it still loads results slow (30-60secs)

![image](https://github.com/aymene69/stremio-jackett/assets/97279898/09677030-7abf-4f10-87ac-66290da3ce97)

**Comment by aymene69** [comment]
I think I'll implement a timeout for my loop. Thanks !

**Comment by karolp1993** [comment]
I'm facing the same issue ;)

**Comment by andronedev** [comment]
i have the same bug

**Comment by aymene69** [comment]
Its fixed and will be pushed in the next release

**Comment by aymene69** [comment]
Fixed
