### ISSUE TITLE
[Bug] Error: ENOENT: no such file or directory

### ISSUE THREAD

**Issue by 9acca9** [aymene69/stremio-jackett#44]
HI.
Im trying the new 1.2.0 version.
And im getting this error.

After 
npm run build
npm start i get

it is working but... when i try to access from mydomain (as i was doing in the version before), now i get this:

```
npm start                                    ✔  panchines@manjaro 

> stremio-addon-jackett@1.2.0 start
> tsx watch dist/index.cjs

Server is running at http://localhost:3000
Error: ENOENT: no such file or directory, stat '/home/panchines/stremio-jackett/dist/frontend/stremio-jackett/index.html'
```

I get that error when trying to access.

So, maybe is something between Nginx and the stremio-jackett because if i go directly to http://192.168.0.166:3000 i reach the web and all is working fine (except, of course, that i cant install the stremio-jackett addon from that location)

I try several different configs in Nginx but all give me the same error.

This is the config in nginx (i was using this, and this was working... but no anymore):
```
location / {
    proxy_pass http://127.0.0.1:3000/;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header Host $host;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
}
```
And why is looking for index.html that is seems not exist.
And also this:
/home/panchines/stremio-jackett/dist/frontend/stremio-jackett/index.html

before "index.html" i see "stremio-jackett". that dont seems right...... i try to change that in "routes.js" (at the end of the file) but keep saying index.html dont exist (and it seems it is not lying)

**Comment by 9acca9** [comment]
i copy the index.hbs to index.html and change the path to 
` /home/panchines/stremio-jackett/dist/frontend/configure/index.html`

and i can now see the file but...... the web dont look good at all. I cant see the palestine flag and also dont see the version
![image](https://github.com/aymene69/stremio-jackett/assets/25393371/c3db6e82-3575-4d22-b479-496ba3b9d995)

and also... cant install because give an error.... that i dont give here because probably all the changes i made were crap.
So, i will just wait for help.
Thanks!

**Comment by hyoretsu** [comment]
You forgot to export the SUBPATH environment variable.
`export SUBPATH=/stremio-jackett npm start`

**Comment by hyoretsu** [comment]
If you wanna switch to dev branch, the latest commit supports setting them via .env

**Comment by 9acca9** [comment]
oh!!!! i see! with that works!!!!!!! and i can install!

But, for other persons like me that dont know how to code, or this settings (lets say), we dont know how to do that (i mean, think about that)

I just follow the instruction for install

"npm run build"
"npm start"

and thats it.

By the way the addon is installed and working, but i dont see the name of the files, look:

![image](https://github.com/aymene69/stremio-jackett/assets/25393371/39d6267c-6a1d-420f-9324-e8a0ee339a59)


And here the terminal with the stremio-jackett working
![image](https://github.com/aymene69/stremio-jackett/assets/25393371/5049158f-76f2-4f94-ba88-50c856a1a49b)

**Comment by 9acca9** [comment]
> If you wanna switch to dev branch, the latest commit supports setting them via .env

mmm, how i can git clone the dev branch?
That fix the thing to just write npm start?

(sorry my ignorance about this subjects)

**Comment by hyoretsu** [comment]
> But, for other persons like me that dont know how to code, or this settings (lets say), we dont know how to do that (i mean, think about that)

We did. We could've documented it better, but it's for this reason that the simpler Docker instructions and the guide exist. Normal people wouldn't mess around with subpaths, running multiple servers in the same machine and whatnot. (That was a personal need of mine actually, that's why I added those features. Not even Torrentio has them)

> By the way the addon is installed and working, but i dont see the name of the files, look:

Noted unfortunately, we'll look into it asap.

> mmm, how i can git clone the dev branch?

git checkout dev && git pull

**Comment by 9acca9** [comment]
ok, thank. I try the docker version but for some...... weird reason i dont get it to work with my nginx.... (maybe i could try again to avoid bother (i will try again))

(i have several service running Trilium/Bookstack/Invidious/Calibre-web and now Jackett and stremio-addon but, i suppose i always have luck to install, also, i dont touch anything in a lot of time and i forgot how was config this and that, and get lost)

but anyway, thanks for all!!!!!!!!!!

**Comment by 9acca9** [comment]
@hyoretsu 
Oh! by the way, when i wrote "think about that", I try to say that "we" (we laymen don't know how to "think" about that)
not that you (programmers) had to think about that.

I just notice this re reading your comment ("We did"). But in fact, anyway you did, lol.
just that, thanks (i dont speak english so.....)

**Comment by hyoretsu** [comment]
I know, and what I mean to say is laymen usually stay away from hard things and go the easy way (Docker/guide) instead of trying to configure a subpath.
