### ISSUE TITLE
Subsequent requests take the same time as the first one

### ISSUE THREAD

**Issue by nfn** [aymene69/stremio-jackett#45]
Subsequent requests take the same time as the first one (stremio app closed between each test)?

I have the default setup using docker and I can see the cached torrents on Jackett.

Shouldn't the subsequent requests be faster since jackett has them cached?

I've tested this by opening stremio, choosing a movie and wait for the results.
Then I close stremio and clear it from memory and reopen it again.

When choosing the same movie, I need to wait the same time as the first request and so on.

**Comment by timknowlden** [comment]
Devs on the discord channel have said they will bring caching to the addon in the future.

**Comment by aymene69** [comment]
Fixed
