### ISSUE TITLE
Prowlarr support

### ISSUE THREAD

**Issue by ericvlog** [aymene69/stremio-jackett#5]
it quite same with jackett ....

so it will working with ?

thanks

**Comment by hongkongkiwi** [comment]
I'm also interested in this, the issue is closed, is it complete?

**Comment by davidemarcoli** [comment]
Hi @hongkongkiwi 
No, it's not completed.
I don't really have time at the moment to add this, but maybe i will have some time in a few weeks...
If you have time, go for it :wink:

**Comment by aymene69** [comment]
Never coming. "Stremio-Jackett"
