### ISSUE TITLE
[Feature] Guide to get add-on working throughout the local network

### ISSUE THREAD

**Issue by aonurgiray** [aymene69/stremio-jackett#54]
Following the guides here I was able to get the add-on working on my Windows PC using the docker image. However, since Stremio only accepts HTTPS connection, I am not able to use the add-on on my TV - installation is done using 127.0.0.1:3000. 

Is there a workaround for this that can be implemented to the add-on or if it is already do-able could we maybe have a guide for this use case? I assume many people would benefit from such a use case.

**Comment by Keklol1245** [comment]
use ngrok for 127.0.0.1:3000 it gives you a https url that works. and just use the standard 127.0.0.1:9117 for the jackett url

**Comment by aonurgiray** [comment]
@Keklol1245  I tried the same but then it gives me error during installation to Stremio:
![image](https://github.com/aymene69/stremio-jackett/assets/75207486/a54306dd-2d2b-4503-acc0-10ea95658232)

**Comment by floxigen** [comment]
> @Keklol1245 I tried the same but then it gives me error during installation to Stremio: ![image](https://private-user-images.githubusercontent.com/75207486/301069549-a54306dd-2d2b-4503-acc0-10ea95658232.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY3MjY1NjksIm5iZiI6MTcwNjcyNjI2OSwicGF0aCI6Ii83NTIwNzQ4Ni8zMDEwNjk1NDktYTU0MzA2ZGQtMmQyYi00NTAzLWFjYzAtMTBlYTk1NjU4MjMyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTMxVDE4Mzc0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM2N2YxN2RhMmE1YzAzNzU4Yzg2MmUzZmE5NTMwMjZhZmU4MzMyNThkYzc4NzdjYmQwNTQ4YThkZWZhZDkzMzUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.FLDy_RjUpzUKGWoEpk03KSJsa3VQgJHWSXmL2jryOMQ)

You need to use traefik to redirect http to https

**Comment by aonurgiray** [comment]
for those encountered similar issue, I could make it work with https://github.com/localtunnel/localtunnel as suggested by Stremio-addon SDK - https://github.com/Stremio/stremio-addon-sdk
