### ISSUE TITLE
[Bug] 'address already in use' when restarting jackett-stremio docker

### ISSUE THREAD

**Issue by Ulinsky** [aymene69/stremio-jackett#57]
**Describe the bug**
Stopping and starting the  jackett-stremio container causes 'address already in use' error

**To Reproduce**
Start the container using provided docker compose.yml, do docker stop jackett-stremio, then docker start jackett-stremio

**Expected behavior**
The docker image used to be restartable

**Screenshots**
![image](https://github.com/aymene69/stremio-jackett/assets/31242994/6a9e2363-8cc1-4a83-85cd-9431026f08a6)

**Your system info (please complete the following information):**
 - OS: Windows 11 with WSL2 Debian
 - Version v1.2.9
 - Docker

**Comment by aymene69** [comment]
Port 3000 is already used. Change it

**Comment by Ulinsky** [comment]
Well it is in use, by the jackett-stremio docker image itself. It works fine once, and then when the container restarts, suddenly it's in use. It starts working again when I do docker compose down, then docker compose up -d. I dont think a different port will change anything (tried 9118, behaves the same)
