### ISSUE TITLE
[Feature] Filter by movie quality 

### ISSUE THREAD

**Issue by nfn** [aymene69/stremio-jackett#61]
Hi

Would be great if could filter the movie quality we would like to see, just like torrentio does.

Ex, let me choose only 1080p and 720p and one result per movie quality.

Thanks

**Comment by 9acca9** [comment]
> Ex, let me choose only 1080p and 720p and one result per movie quality.

This will be good also for me, i just have a projector for 1080. So, more than that is just superfluous.
Thanks

**Comment by kekkers23** [comment]
Also include filtering for HDR/HDR+/DV content 
![image](https://github.com/aymene69/stremio-jackett/assets/5749788/23da3d86-57c3-4687-b064-e6e6d2e8b0ed)

**Comment by aymene69** [comment]
Implemented
