### ISSUE TITLE
[Feature] Filter by file size

### ISSUE THREAD

**Issue by kekkers23** [aymene69/stremio-jackett#63]
As with Torrentio, it would be great to have a max file size filter for lower-end devices that can't handle a 150GB movie stream

**Comment by aymene69** [comment]
This is a thing already

**Comment by kekkers23** [comment]
> This is a thing already

Sorry perhaps bad wording on my part, you can ORGANISE the list by biggest to smallest and vice versa.

What I'm requesting is a way to cap the max filesize e.g. do not display files larger than X GB.

**Comment by hyoretsu** [comment]
It's not possible in Jackett, and we'd still need to fetch those results. If we were to implement this, it'd be manual filtering work. It's not hard, but it's even easier to just not play those results.

https://github.com/Jackett/Jackett/issues/12854

**Comment by aymene69** [comment]
Implemented
