### ISSUE TITLE
[Bug] Anime IDs from kitsu catalogs throwing errors

### ISSUE THREAD

**Issue by deathbeam** [aymene69/stremio-jackett#65]
Result of id in routes.js:

[ 'kitsu', '46474', '11' ]

E.g the prefix kitsu is not handled (which is what the kitsu catalog addon adds I assume)

You can aso see that the season info is missing there and it only contains episode and kitsu id, currently looks like the routes code always assumes format ID:SEASON:EPISODE

**Comment by aymene69** [comment]
Animes are MESSED up with Jackett. Duplicate of #16
