### ISSUE TITLE
Forcing http in host (req.protocol) [Bug]

### ISSUE THREAD

**Issue by ash32152** [aymene69/stremio-jackett#66]
**Describe the bug**
I'm unable to play any of the scraped links as it's passing the url back as http://yourdomain.tld/getstream rather than https://

**To Reproduce**
stremio-jackett behind traefik, connecting to a jackett instance behind traefik protected by SSL, search for a movie and look in the logs for the console.log host

**Expected behavior**
play the link selected, instead it fails as I'm using stremio app which uses https:// and requires https://, the app was installed under the https://addon.tld

**Screenshots**

**Your system info (please complete the following information):**
 - OS: [e.g. Ubuntu]
 - Docker or Node ?

**Additional context**
16:24:31 0|stremio-jackett  | **http**://stremjack.tld.uk
16:24:31 0|stremio-jackett  | Searching on Jackett, will return debrid links...
16:24:31 0|stremio-jackett  | https://jackdebrid.tld.uk/api/v2.0/indexers/all/results/torznab/api?apikey=<private>&t=movie&cat=2000&q=The%20Hill&year=2023
16:24:38 0|stremio-jackett  | 10
16:24:49 0|stremio-jackett  | Torrent info: The.Hill.2023.720p.AMZN.WEBRip.800MB.x264-GalaxyRG
16:24:49 0|stremio-jackett  | Getting RD link...
16:24:49 0|stremio-jackett  | **http**://stremjack.tld.uk/getStream/realdebrid/

**Comment by aymene69** [comment]
You used the guide?

**Comment by ash32152** [comment]
Yes, i dont host it via oracle/elfhosted or use duckdns, i have a paid for tld, I'm hosting this with traefik, already have certs, it has a https entrypoint, I browse to it via https, some reason it spits out the getstream path as http:// in the container.

**Comment by aymene69** [comment]
put use tls in traefik label for the container

**Comment by ash32152** [comment]
it is... I only expose 443, have .tls=true on all my labels, as mentioned, browse both fine via https, it's when the add-on tries to output the getstream link it downgrades to http.

no probs, I'm using a different jackett add-on that works, thanks though :)
