### ISSUE TITLE
[Bug] Playback errors on iOS (using Web App with VLC set as external player)

### ISSUE THREAD

**Issue by BarristQL** [aymene69/stremio-jackett#67]
**Describe the bug**

- Finding playback errors for many links when using web app in iOS. (Streams play externally on VLC)
- Strangely, a few links do work, but others don't. 

**To Reproduce**
- Search for movie/show
- Try to play one of the links
- VLC opens and shows "Playback failed" message
- tried the same links from Stremio search in Android (GoogleTV with Chromecast), Windows (app and web app) and they appear to work correctly there
- same streams from Stremio on web app on iOS work when selecting Outplayer as the external player

**Screenshots**
This error happens when clicking on the stream and the playback fails.
<img width="783" alt="image" src="https://github.com/aymene69/stremio-jackett/assets/97279898/6ea94c79-7495-4cfc-a6f9-baff146458c6">

**Your system info (please complete the following information):**
- Set up using newbie guide on Oracle Cloud
- Latest stremio version 1.3.5
- iOS devices tested (iphone, ipad)

**Comment by BarristQL** [comment]
Suspecting its something related to VLC
- Switched external player to Outplayer, and links appear to work fine. Links from Torrentio work fine with VLC. 
- Checked logs in VLC debug:
`ERR] HTTP 404 error [DBG] connection failed [DBG] shutdown TLS session [DBG] close TLS session [DBG] close secure transport client [DBG] no access modules matched [ERR] Your input can't be opened [ERR] VLC is unable to open the MRL 'http://[redacted url]/addon/getStream/realdebrid/[redacted api key]/bWFnbmV0Oj94dD11cm46YnRpaDo4ODZEODAzMDg1RjlBMEQ0MkI1NkIxRjgwODU4RTJDQTU5QTc3RUIwJmRuPUludGVyc3RlbGxhciUyMDIwMTQlMjA0SyUyMEhEUiUyMDIxNjBwJTIwQkRSaXAlMjBJdGElMjBFbmclMjB4MjY1JTIwTkFIT00mdHI9dWRwJTNBJTJGJTJGbW92aWVzLnpzdy5jYSUzQTY5NjklMkZhbm5vdW5jZSZ0cj11ZHAlM0ElMkYlMkZleG9kdXMuZGVzeW5jLmNvbSUzQTY5NjklMkZhbm5vdW5jZSZ0cj11ZHAlM0ElMkYlMkZ0cmFja2VyLm9wZW50cmFja3Iub3JnJTNBMTMzNyUyRmFubm91bmNlJnRyPXVkcCUzQSUyRiUyRnA0cC5hcmVuYWJnLmNvbSUzQTEzMzclMkZhbm5vdW5jZSZ0cj11ZHAlM0ElMkYlMkZ0cmFja2VyLnRoZW9rcy5uZXQlM0E2OTY5JTJGYW5ub3VuY2UmdHI9dWRwJTNBJTJGJTJGZXhwbG9kaWUub3JnJTNBNjk2OSUyRmFubm91bmNlJnRyPXVkcCUzQSUyRiUyRnRyYWNrZXIudGhlcmFyYmcuY29tJTNBNjk2OSUyRmFubm91bmNlJnRyPXVkcCUzQSUyRiUyRnRyYWNrZXIxLmJ0Lm1vYWNrLmNvLmtyJTNBODAlMkZhbm5vdW5jZSZ0cj11ZHAlM0ElMkYlMkZ0cmFja2VyLm9wZW5iaXR0b3JyZW50LmNvbSUzQTY5NjklMkZhbm5vdW5jZSZ0cj11ZHAlM0ElMkYlMkZvcGVuLmRlbW9uaWkuY29tJTNBMTMzNyUyRmFubm91bmNlJnRyPXVkcCUzQSUyRiUyRm9wZW50cmFja2VyLmkycC5yb2NrcyUzQTY5NjklMkZhbm5vdW5jZSZ0cj11ZHAlM0ElMkYlMkZ0cmFja2VyLnRoZXJhcmJnLnRvJTNBNjk2OSUyRmFubm91bmNlJnRyPXVkcCUzQSUyRiUyRnRyYWNrZXIubWlycm9yYmF5Lm9yZyUzQTY5NjklMkZhbm5vdW5jZSZ0cj11ZHAlM0ElMkYlMkZvcGVuLnN0ZWFsdGguc2klM0E4MCUyRmFubm91bmNlJnRyPXVkcCUzQSUyRiUyRnRyYWNrZXIubW9la2luZy5tZSUzQTY5NjklMkZhbm5vdW5jZSZ0cj11ZHAlM0ElMkYlMkZ0cmFja2VyLnQtcmIub3JnJTNBNjk2OSUyRmFubm91bmNlJnRyPXVkcCUzQSUyRiUyRnRyYWNrZXIudG9ycmVudC5ldS5vcmclM0E0NTElMkZhbm5vdW5jZSZ0cj11ZHAlM0ElMkYlMkZ0cmFja2VyLnRpbnktdnBzLmNvbSUzQTY5NjklMkZhbm5vdW5jZQ'. Check the log for details. [DBG] removing module "audiounit_ios"
`

**Comment by aymene69** [comment]
Fixed in new version
