### ISSUE TITLE
[Feature] debrid-link.com

### ISSUE THREAD

**Issue by haircut773** [aymene69/stremio-jackett#69]
**Is your feature request related to a problem? Please describe.**
no

**Describe the solution you'd like**
With Torrentio, Debrid-link was available but with Streamio-jackett is not. Do you have planned to add it ?

This could help you maybe: https://github.com/TheBeastLT/torrentio-scraper/blob/master/addon/moch/debridlink.js

**Comment by aymene69** [comment]
Not planned

**Comment by haircut773** [comment]
I can try to implement if you want?

**Comment by aymene69** [comment]
Do a PR. With fetch only please
