### ISSUE TITLE
[Feature] Any chance for a proper Stremio addon?

### ISSUE THREAD

**Issue by lothar-cell** [aymene69/stremio-jackett#70]
**Is your feature request related to a problem? Please describe.**
I would be great if it could be installed via a link or from inside Stremio.

**Describe the solution you'd like**
I'd like to install in via Stremio or the addon site.

**Describe alternatives you've considered**
There's an other Jackett addon that appeared recently, but it's sloppy and contains propaganda.

**Additional context**
Not applicable

**Comment by aymene69** [comment]
It isn't possible. You can't do it.

**Comment by hyoretsu** [comment]
This is only possible if someone hosts the addon by themselves and makes his URL public. He'd have to handle all the incoming traffic and spend money, so as of now it isn't ideal. (There's Beamup, but I don't know how that works)

**Comment by lothar-cell** [comment]
How about this? https://elfhosted.com
I've seen two addons built on this already.

**Comment by lothar-cell** [comment]
Also, there's a local addon manager in development, similar to PimpMyStremio.
