### ISSUE TITLE
[Bug] wait() when fetching and retrying for RD links does not actually wait

### ISSUE THREAD

**Issue by matukaa** [aymene69/stremio-jackett#72]
**Describe the bug**
`await wait(5000)` does not actually do anything in any of the `getMovieProviderLink` files, it will retry per frame instead of waiting 5 seconds between tries.

**To Reproduce**
Try to open any result fetched from Jackett which is not yet cached by RD (in my case).

**Expected behavior**
Wait the expected amount of time between retries.

**Screenshots**
![image](https://github.com/aymene69/stremio-jackett/assets/7106864/72997b43-1227-4cf0-992f-01ba4b82346e)

**Your system info (please complete the following information):**
 - OS: Windows
 - Docker or Node - both

**Additional context**
`wait()` creates a `Promise` but it does not return it, so the `await` does not receive any `Promise` to actually await for. It just instantly steps over and repeats the loops.

**Comment by aymene69** [comment]
Fixed
