### ISSUE TITLE
[Feature] Support season packs

### ISSUE THREAD

**Issue by wogam** [aymene69/stremio-jackett#74]
**Is your feature request related to a problem? Please describe.**
Support season packs. Almost all content beyond a year old is difficult to find in individual episodes, so season packs are important here. This is also for feature parity with torrentio.

**Describe the solution you'd like**
I'm not sure how it would be support for torrent streaming, but for debrid services usually they return an array with the order of the links corresponding the episode.

**Describe alternatives you've considered**
There aren't any equivalent alternatives.

**Additional context**
Torrentio example:
![image](https://github.com/aymene69/stremio-jackett/assets/48340127/87919019-8b8e-4c17-ad98-3c96125dae00)
(Almost all the links here are from season packs, you can see this from the first line of each result)

**Comment by aymene69** [comment]
We already do
