### ISSUE TITLE
Error of autoupdate tool to update from 2.0.0 to 2.0.1 [Bug]

### ISSUE THREAD

**Issue by xancandal** [aymene69/stremio-jackett#78]
After updating to version 2.0.0, the auto update tool is not able to update to version 2.0.1

I get the following error:

![image](https://github.com/aymene69/stremio-jackett/assets/1079504/1a7a0280-ae04-41da-8382-2745938267bb)

Following the guide, using Oracle Cloud. With the only note that I have to find out the "IPAddress" with: docker inspector [container ID of lscr.io/linuxserver/jackett:latest], to write, for example, http://172.20.0.4:9117 in "Jackett URL " in /addon/configure. Otherwise I don't get results in Stremio.

The problem persists even after performing a clean installation from scratch.

**Comment by xancandal** [comment]
Ok, thank you very much for your response. One last question, is there a way I can update from version 2.0.0. to version 2.0.1 manually?. Since I have the same error as the one reported in "Playback errors on iOS (using Web App with VLC set as external player)" and I have seen that version 2.0.1 is fixed and I would like to try it .

**Comment by aymene69** [comment]
there is absolutely no changes from 2.0.0 to 2.0.1 except a debug console.log left.

**Comment by xancandal** [comment]
Sorry, I saw this commit https://github.com/aymene69/stremio-jackett/commit/8409ead6f4c147411a4e8598c56dfd083e49d455 and I thouht that "Playback errors on iOS (using Web App with VLC set as external player)" was already fixed.

![image](https://github.com/aymene69/stremio-jackett/assets/1079504/896b2050-afe6-4ea8-8624-a84dbf399f56)
