### ISSUE TITLE
Installation on a seperate machine, ERR_OPENING_MEDIA Failed to fetch

### ISSUE THREAD

**Issue by Meow-ops** [aymene69/stremio-jackett#8]
Trying to install the add-on on a separate machine.
The docker jackett server running on 192.168.1.2, the add-on docker also running  on 192.168.1.2. The host computer has the 192.168.1.3 IP
When trying to install the add-on, stremio displays a pop-up saying "ERROR_OPENING_MEDIA":
![image](https://github.com/aymene69/stremio-jackett/assets/5023842/96e1c3c8-b4e6-439e-bef3-59fe760813bc)

**Comment by aymene69** [comment]
try new version
