### ISSUE TITLE
[Feature] Hide "Unknown" quality results and other quality attributes

### ISSUE THREAD

**Issue by wogam** [aymene69/stremio-jackett#93]
**Is your feature request related to a problem? Please describe.**
"Unknown" quality releases are populated in the results, cluttering then. Additionally, hide certain types of qualities, such as remuxs and HDR, which may be unsupported on certain devices. This would bring feature parity to torrentio.

**Describe the solution you'd like**
Ability to hide "Unknown", "Remux", "HDR", "Dolby Vision"

**Describe alternatives you've considered**
None

**Additional context**
<img width="523" alt="Screenshot 2024-02-06 at 22 34 50" src="https://github.com/aymene69/stremio-jackett/assets/48340127/5d11a631-5103-4714-a104-66241d5c9405">
(Screen shot from torrentio filter selection)

<img width="191" alt="Screenshot 2024-02-06 at 22 35 45" src="https://github.com/aymene69/stremio-jackett/assets/48340127/5c298e95-cf13-424c-aaf1-d42293b0a4ee">
(Example of unknown quality)

**Comment by aymene69** [comment]
Fixed
