### ISSUE TITLE
[Feature] Support season packs 

### ISSUE THREAD

**Issue by wogam** [aymene69/stremio-jackett#95]
**Is your feature request related to a problem? Please describe.**
Please see #74, I don't think I explained the feature correctly
The add-on only searches for (example) S01E01 when it should, in addition or maybe as an option, search for S01. See differences below.

**Describe the solution you'd like**
Search for SXX in addition to SXXEXX

**Describe alternatives you've considered**
None

**Additional context**

<img width="1186" alt="Screenshot 2024-02-06 at 23 03 43" src="https://github.com/aymene69/stremio-jackett/assets/48340127/0a9838c2-159f-42c9-9b04-e52a71acfe19">
Just two results when searching for individual episodes

<img width="1026" alt="Screenshot 2024-02-06 at 23 04 12" src="https://github.com/aymene69/stremio-jackett/assets/48340127/020fe37d-f915-44e7-aac9-105134dca83d">
Multiple results when searching for packs

**Comment by aymene69** [comment]
Now added in 3.0.0
